language: csharp
dotnet: 2.2
sudo: required
solution: "./MultiCurrencyMoney/MultiCurrencyMoney.sln"
dist: xenial
install:
  - travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./MultiCurrencyMoney/MultiCurrencyMoney.sln
script:
  - dotnet build ./MultiCurrencyMoney/MultiCurrencyMoney.sln
  - dotnet test ./MultiCurrencyMoney/MultiCurrencyMoney.sln
